export const LOAD_ARTICLES_START = 'LOAD_ARTICLES_START';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL';

export const SELECT_ARTICLE = 'SELECT_ARTICLE';

export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_FAIL = 'LOAD_COMMENTS_FAIL';

export const LOAD_REPLIES_START = 'LOAD_REPLIES_START';
export const LOAD_REPLIES_SUCCESS = 'LOAD_REPLIES_SUCCESS';
export const LOAD_REPLIES_FAIL = 'LOAD_REPLIES_FAIL';

export const ADD_COMMENT_START = 'ADD_COMMENT_START';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const ADD_REPLY_START = 'ADD_REPLY_START';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL';

export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'ADD_PREV_PAGEREPLY_FAIL';
